version: "3.8"
services:
  database:
    image: postgres:13.3
    container_name: database
    env_file:
      - .env
  redis:
    image: redis:latest
    container_name: redis
    env_file:
      - .env
  backend:
    container_name: backend
    env_file:
      - .env
    ports:
      - "1323:1323"
    build:
      context: .
      dockerfile: Dockerfile-backend
    depends_on:
      - database
      - redis
