version: "3.8"
services:
  database:
    image: postgres:latest
    container_name: database
    env_file:
      - .env
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=database
    ports:
      - "5432:5432"
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
  backend:
    container_name: backend
    env_file:
      - .env
    ports:
      - "1323:1323"
    build:
      context: .
      dockerfile: backend/Dockerfile-backend
    depends_on:
      - database
      - redis
