CREATE TABLE IF NOT EXISTS todo_list (
		id SERIAL,
		title VARCHAR(255) NOT NULL,
    	username VARCHAR(255) NOT NULL,
		created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP